
-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Create Restaurantes table
CREATE TABLE IF NOT EXISTS "Restaurantes" (
    "id" UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "nome" TEXT,
    "email" TEXT UNIQUE,
    "senha" TEXT,
    "telefone" TEXT,
    "quantidade_mesas" TEXT,
    "quantidade_max_mesas" TEXT,
    "horario_fecha_cozinha" TEXT,
    "horario_abertura" TEXT,
    "horario_fechamento" TEXT,
    "fechar_mesa_auto" BOOLEAN DEFAULT TRUE,
    "alertas_piscantes" BOOLEAN DEFAULT TRUE,
    "sons_habilitados" BOOLEAN DEFAULT TRUE,
    "alerta_estoque_baixo" INTEGER DEFAULT 15,
    "alerta_estoque_critico" INTEGER DEFAULT 5,
    "impressao_auto" BOOLEAN DEFAULT FALSE
);

-- Create Produtos table
CREATE TABLE IF NOT EXISTS "Produtos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "nome" TEXT,
    "preco" TEXT, -- App uses text/string for price often, but numeric is better. Keeping text to match types.ts
    "restaurante_id" UUID REFERENCES "Restaurantes"("id"),
    "categoria" TEXT,
    "estacao" TEXT,
    "estoque" INTEGER DEFAULT 0,
    "estoque_minimo" INTEGER DEFAULT 10,
    "descricao" TEXT,
    "ativo" BOOLEAN DEFAULT TRUE
);

-- Create Pedidos table
CREATE TABLE IF NOT EXISTS "Pedidos" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "mesa" TEXT,
    "itens" TEXT,
    "quantidade" TEXT,
    "Subtotal" TEXT,
    "status" TEXT,
    "restaurante_id" UUID REFERENCES "Restaurantes"("id"),
    "descricao" TEXT
);

-- Create Usuários table (Clients)
CREATE TABLE IF NOT EXISTS "Usuários" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "created_at" TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    "nome" TEXT,
    "telefone" TEXT,
    "quantas_vezes_foi" TEXT DEFAULT '0',
    "id_restaurante" UUID, -- Can link to Restaurantes if needed
    "mesa_atual" TEXT
);

-- Insert Test Restaurant
INSERT INTO "Restaurantes" (nome, email, senha, quantidade_mesas, quantidade_max_mesas)
VALUES ('Restaurante Teste', 'teste@pedeai.com', '123456', '10', '20')
ON CONFLICT (email) DO NOTHING;
